apiVersion: apps/v1
kind: Deployment
metadata:
  name: revitage
  labels:
    app: revitage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revitage
  template:
    metadata:
      labels:
        app: revitage
    spec:
      containers:
        - name: revitage
          image: vlad1894/my-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb.mongodb.svc.cluster.local:27017/"
            - name: MONGO_DB_NAME
              value: "revitage"
            - name: ALLOWED_HOSTS
              value: "*"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
      imagePullSecrets:
        - name: dockerhub-secret
