apiVersion: v1
kind: Service
metadata:
  name: revitage
  labels:
    app: revitage
spec:
  selector:
    app: revitage
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP